firstname=input("Please enetr your first name : ")
secondname=input("please enter your second name : ")
age=int(input("Please enter your age : "))
contact=int(input("please enter your 10 digit contact number : "))
email=input("please enter your email address : ")
print("-------Your Details--------")
print("Name= ",firstname+" "+secondname)
print("Age= ",age)
print("Contact no.= ",contact)
print("Email Id= ",email)

